### ISSUE TITLE
Error on server stop/plugin disable

### ISSUE THREAD

**Issue by TheWranger** [VolmitSoftware/Gloss#11]
Error in console on server stop/plugin disable:
```
05.10 21:34:23 [Server] ERROR Could not pass event PluginDisableEvent to Gloss v1.0
05.10 21:34:23 [Server] INFO org.bukkit.event.EventException: null
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:702) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
05.10 21:34:23 [Server] INFO Caused by: java.util.NoSuchElementException: tiny-Gloss
05.10 21:34:23 [Server] INFO at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:451) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO at com.comphenix.protocol.injector.netty.PipelineProxy.remove(PipelineProxy.java:318) ~[?:?]
05.10 21:34:23 [Server] INFO at com.volmit.gloss.volume.bukkit.nms.TinyProtocol.close(TinyProtocol.java:212) ~[?:?]
05.10 21:34:23 [Server] INFO at com.volmit.gloss.volume.bukkit.nms.TinyProtocol.onPluginDisable(TinyProtocol.java:117) ~[?:?]
05.10 21:34:23 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor315.execute(Unknown Source) ~[?:?]
05.10 21:34:23 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1563]
05.10 21:34:23 [Server] INFO ... 11 more
```
Running PaperSpigot 1.12.2 - Build 1563

**Comment by cyberpwnn** [comment]
That's weird. Thanks.

**Comment by cyberpwnn** [comment]
Fixed
