### ISSUE TITLE
Error when shutting down

### ISSUE THREAD

**Issue by Firefox8821** [VolmitSoftware/Gloss#23]
```
[09:22:47 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.volmit.gloss.services.PacketSVC@647e4c5b while not enabled
[09:22:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:541)
[09:22:47 WARN]:        at com.volmit.gloss.primal.bukkit.plugin.PrimalPlugin.registerListener(PrimalPlugin.java:158)
[09:22:47 WARN]:        at com.volmit.gloss.util.U.getService(U.java:69)
[09:22:47 WARN]:        at com.volmit.gloss.services.ContextSVC.start(ContextSVC.java:124)
[09:22:47 WARN]:        at com.volmit.gloss.util.U.getService(U.java:68)
[09:22:47 WARN]:        at com.volmit.gloss.services.ExecSVC$4.run(ExecSVC.java:78)
[09:22:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:22:47 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[09:22:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:515)
[09:22:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:220)
[09:22:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:216)
[09:22:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.scheduleAsyncRepeatingTask(CraftScheduler.java:211)
[09:22:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.scheduleAsyncDelayedTask(CraftScheduler.java:162)
[09:22:47 WARN]:        at com.volmit.gloss.primal.bukkit.sched.J.a(J.java:195)
[09:22:47 WARN]:        at com.volmit.gloss.primal.bukkit.sched.A.<init>(A.java:12)
[09:22:47 WARN]:        at com.volmit.gloss.services.ExecSVC$1.<init>(ExecSVC.java:32)
[09:22:47 WARN]:        at com.volmit.gloss.services.ExecSVC.start(ExecSVC.java:32)
[09:22:47 WARN]:        at com.volmit.gloss.util.U.getService(U.java:68)
[09:22:47 WARN]:        at com.volmit.gloss.services.ContextSVC.start(ContextSVC.java:125)
[09:22:47 WARN]:        at com.volmit.gloss.util.U.getService(U.java:68)
[09:22:47 WARN]:        at com.volmit.gloss.services.ExecSVC$4.run(ExecSVC.java:78)
[09:22:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:22:47 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.volmit.gloss.services.ContextSVC@78fff752 while not enabled
[09:22:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:541)
[09:22:47 WARN]:        at com.volmit.gloss.primal.bukkit.plugin.PrimalPlugin.registerListener(PrimalPlugin.java:158)
[09:22:47 WARN]:        at com.volmit.gloss.util.U.getService(U.java:69)
[09:22:47 WARN]:        at com.volmit.gloss.services.ExecSVC$4.run(ExecSVC.java:78)
[09:22:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:22:47 WARN]: Exception in thread "Gloss Scheduler 1" java.lang.NullPointerException
[09:22:47 WARN]:        at com.volmit.gloss.services.ExecSVC$4.run(ExecSVC.java:78)
[09:22:47 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by cyberpwnn** [comment]
Was Gloss reloaded via BileTools/Plugman/Whatever?

**Comment by Firefox8821** [comment]
> Was Gloss reloaded via BileTools/Plugman/Whatever?

No, it was not. This is when I start the server and then shut it down. This also occurs during a restart, it's on my public server.

**Comment by cyberpwnn** [comment]
Fixed
