### ISSUE TITLE
Header/footer new lines?

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Gloss#33]
```yaml
tablist:
  header: '&6&l&sExample'
  footer: '\nexample'
```

It would be nice to be able to use this format:
```yaml
tablist:
  header: 
  - "Test 1"
  - "Test 2"
  - "Test 3"
  footer: 
  - "Test 1"
  - "Test 2"
  - "Test 3"
```

**Comment by LogGits** [comment]
forgot to mention but `\n` causes errors when used in header/footer (hence why i requested this):
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 49 path $.text
at com.google.gson.internal.Streams.parse(Streams.java:60)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497)
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522)
at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:404)
at mortar.api.nms.Catalyst13.packetTabHeaderFooter(Catalyst13.java:476)
at mortar.api.nms.NMP$PLAYER.sendTablist(NMP.java:35)
at com.volmit.gloss.util.PlayerTab.update(PlayerTab.java:31)
at com.volmit.gloss.controllers.ContextController.update(ContextController.java:289)
at com.volmit.gloss.controllers.ExecController$4.run(ExecController.java:89)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 49 path $.text
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1550)
at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1004)
at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
at com.google.gson.internal.Streams.parse(Streams.java:48)
... 10 more
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522)
at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:404)
at mortar.api.nms.Catalyst13.packetTabHeaderFooter(Catalyst13.java:476)
at mortar.api.nms.NMP$PLAYER.sendTablist(NMP.java:35)
at com.volmit.gloss.util.PlayerTab.update(PlayerTab.java:31)
at com.volmit.gloss.controllers.ContextController.update(ContextController.java:289)
at com.volmit.gloss.controllers.ExecController$4.run(ExecController.java:89)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 33 path $.text
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1550)
at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1004)
at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
at com.google.gson.internal.Streams.parse(Streams.java:48)
... 10 more
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 29 path $.text
at com.google.gson.internal.Streams.parse(Streams.java:60)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497)
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522)
at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:404)
at mortar.api.nms.Catalyst13.packetTabHeaderFooter(Catalyst13.java:476)
at mortar.api.nms.NMP$PLAYER.sendTablist(NMP.java:35)
at com.volmit.gloss.util.PlayerTab.update(PlayerTab.java:31)
at com.volmit.gloss.controllers.ContextController.update(ContextController.java:289)
at com.volmit.gloss.controllers.ExecController$4.run(ExecController.java:89)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 29 path $.text
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1550)
at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1004)
at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
at com.google.gson.internal.Streams.parse(Streams.java:48)
... 10 more
```

**Comment by SwiftSwamp** [comment]
Update and try again, I'm no longer getting any errors. I believe it was a mortar issue.

**Comment by LogGits** [comment]
@SwiftSwamp it still happens. My usage was `&6&l&sTest server\ntest`

**Comment by DavidRockin** [comment]
Can you try to escape it using `\\n`

**Comment by LogGits** [comment]
it says `Test server\ntest` in the tablist and spams this error:
```
18/07/2019 05:10:16
05:10:16at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522)
at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:404)
at mortar.api.nms.Catalyst13.packetTabHeaderFooter(Catalyst13.java:480)
at mortar.api.nms.NMP$PLAYER.sendTablist(NMP.java:35)
at com.volmit.gloss.util.PlayerTab.update(PlayerTab.java:31)
at com.volmit.gloss.controllers.ContextController.update(ContextController.java:289)
at com.volmit.gloss.controllers.ExecController$4.run(ExecController.java:89)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 33 path $.text
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1550)
at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1004)
at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
at com.google.gson.internal.Streams.parse(Streams.java:48)
... 10 more
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 29 path $.text
at com.google.gson.internal.Streams.parse(Streams.java:60)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497)
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522)
at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:404)
at mortar.api.nms.Catalyst13.packetTabHeaderFooter(Catalyst13.java:480)
at mortar.api.nms.NMP$PLAYER.sendTablist(NMP.java:35)
at com.volmit.gloss.util.PlayerTab.update(PlayerTab.java:31)
at com.volmit.gloss.controllers.ContextController.update(ContextController.java:289)
at com.volmit.gloss.controllers.ExecController$4.run(ExecController.java:89)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 29 path $.text
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1550)
at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1004)
at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
at com.google.gson.internal.Streams.parse(Streams.java:48)
... 10 more
```

**Comment by LogGits** [comment]
Also instead of fixing the \n you could make header/footer a List similar to `motd.texts`
```yaml
motd:
  enabled: false
  texts:
  - "One MOTD per line. \n is allowed."
  - You can use &cColor Codes
  - '<3 :airplane: Emojis are supported'
  - "Each mot is randomly selected \nper serverlist ping."
```

**Comment by DavidRockin** [comment]
So the plugin does support multi lines, you just need to use `\n` Although somehow GSON freaks out when it attempts to build the JSON, it just doesnt want to escape the new line character. It has been fixed for 1.3.0 and mortar 1.0.70.

In the meantime can you see if this works for you?
```yaml
tablist:
  header: |-
    &8=====================
    &d&lGloss &r&8&sHeader&r
    &dMultiple lines!
    &r
  footer: |-
    &r
    &d&lGloss &r&8&sFooter&r
    &qVisit our website at &lvolmit.com
```

**Comment by LogGits** [comment]
Yes that does work but the issue with it is that `&s` goes over multiple lines, that's why i was suggesting the List configuration.

**Comment by DavidRockin** [comment]
Its the way Minecraft handles headers and footers. The list configuration would do the same thing, because each string entry would internally have to be concatenated with a new line char. You can just use `&r` to reset the text
