### ISSUE TITLE
/hologram line

### ISSUE THREAD

**Issue by huynhqtienvtag** [VolmitSoftware/Gloss#41]
# When I use "/hologram line" and click on a line, it gets stuck
![image](https://media.giphy.com/media/8coK75HzwR3SBboVfs/giphy.gif)
Sorry if the gif is not smooth

# Log
```
[10:16:43] [Craft Scheduler Thread - 29/WARN]: [Mortar] Plugin Mortar v1.0.17 generated an exception while executing task 55534
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:709) ~[patched_1.13.2.jar:git-Paper-561]
	at mortar.util.text.RTX.tellRawTo(RTX.java:276) ~[?:?]
	at com.volmit.gloss.command.CommandEditHologramLine$1.run(CommandEditHologramLine.java:117) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-561]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-561]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by cyberpwnn** [comment]
Fixed in 1.0.17 (will be released sometime today)
