### ISSUE TITLE
1.11.2 CmodOp @ Board Load

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/Gloss#44]
```
[08:44:35 WARN]: java.util.ConcurrentModificationException
[08:44:35 WARN]:        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
[08:44:35 WARN]:        at java.util.ArrayList$Itr.next(ArrayList.java:859)
[08:44:35 WARN]:        at mortar.lang.collection.GList.copy(GList.java:635)
[08:44:35 WARN]:        at com.volmit.gloss.controllers.BoardController.load(BoardController.java:206)
[08:44:35 WARN]:        at com.volmit.gloss.controllers.BoardController.reload(BoardController.java:157)
[08:44:35 WARN]:        at com.volmit.gloss.controllers.BoardController.lambda$1(BoardController.java:233)
[08:44:35 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[08:44:35 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[08:44:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:44:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:44:35 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by cyberpwnn** [comment]
Fixed in 1.0.17
