### ISSUE TITLE
Gloss import CMI

### ISSUE THREAD

**Issue by Frerduro** [VolmitSoftware/Gloss#47]
Getting an error when I attempt to import holograms from CMI
```
[17:29:23 INFO]: Frerduro issued server command: /gloss convert cmi
[17:29:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gloss' in plugin Gloss v1.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-3cb9dcb-8b1588e]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-3cb9dcb-8b1588e]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NoSuchMethodError: com.Zrips.CMI.Modules.Holograms.CMIHologram.getCenterLocation()Lorg/bukkit/Location;
at com.volmit.gloss.inject.CMIViolator.runConversion(CMIViolator.java:45) ~[Gloss.jar:?]
at com.volmit.gloss.command.CommandConvertCMIHolograms.handle(CommandConvertCMIHolograms.java:32) ~[Gloss.jar:?]
at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:85) ~[Mortar.jar:?]
at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:99) ~[Mortar.jar:?]
at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:99) ~[Mortar.jar:?]
at mortar.bukkit.plugin.MortarPlugin.onCommand(MortarPlugin.java:469) ~[Mortar.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-3cb9dcb-8b1588e]
... 15 more
```

**Comment by cyberpwnn** [comment]
What version of cmi do you have?
