### ISSUE TITLE
Exception thrown when creating a lit source

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/Gloss#58]
```
[18:52:58 ERROR]: stopTiming called async for world - chunkLoad - TileTicks
[18:52:58 WARN]: java.lang.Throwable
[18:52:58 WARN]:        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[18:52:58 WARN]:        at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:459)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[18:52:58 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:135)
[18:52:58 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:117)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:145)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:604)
[18:52:58 WARN]:        at org.bukkit.Location.getChunk(Location.java:78)
[18:52:58 WARN]:        at com.volmit.gloss.api.display.LitSource.setPosition(LitSource.java:51)
[18:52:58 WARN]:        at com.volmit.gloss.context.GlossDescriptor.setLocation(GlossDescriptor.java:102)
[18:52:58 WARN]:        at com.volmit.gloss.context.GlossDescriptor.fromJSON(GlossDescriptor.java:187)
[18:52:58 WARN]:        at com.volmit.gloss.context.GlossDescriptor.<init>(GlossDescriptor.java:48)
[18:52:58 WARN]:        at com.volmit.gloss.controllers.SourceController.load(SourceController.java:149)
[18:52:58 WARN]:        at com.volmit.gloss.controllers.SourceController$1.run(SourceController.java:191)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[18:52:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:52:58 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[18:52:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:52:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:52:58 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by cyberpwnn** [comment]
Fixed in 1.0.25
