### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CraftSteamG** [VolmitSoftware/Gloss#60]
Console keeps getting spammed with this

```> [23:06:20] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [23:06:20] [Server thread/WARN]: at mortar.api.scm.SCMController.getSelection(SCMController.java:263)
> [23:06:20] [Server thread/WARN]: at mortar.api.scm.SCMController.tick(SCMController.java:284)
> [23:06:20] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
> [23:06:20] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
> [23:06:20] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [23:06:20] [Server thread/WARN]: at mortar.api.scm.SCMController.getSelection(SCMController.java:263)
> [23:06:20] [Server thread/WARN]: at mortar.api.scm.SCMController.tick(SCMController.java:284)
> [23:06:20] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
> [23:06:20] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
> [23:06:20] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [23:06:20] [Server thread/WARN]: at mortar.api.scm.SCMController.getSelection(SCMController.java:263)
> [23:06:20] [Server thread/WARN]: at mortar.api.scm.SCMController.tick(SCMController.java:284)
> [23:06:20] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
> [23:06:20] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
> [23:06:20] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
> [23:06:20] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)```

**Comment by DavidRockin** [comment]
Issue with mortar, update mortar.
