### ISSUE TITLE
2 Issues!

### ISSUE THREAD

**Issue by Firefox8821** [VolmitSoftware/Gloss#62]
```
[22:03:19] [Server thread/INFO]: [Gloss] Disabling Gloss v1.0.26
[22:03:19] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[22:03:19] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[22:03:19] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:03:19] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[22:03:19] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[22:03:19] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:03:19] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[22:03:19] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[22:03:19] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:03:19] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[22:03:19] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[22:03:19] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[22:03:19] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[22:03:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[22:03:19] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[22:03:19] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)


-------------------------------------------------------------------------------------------



SECOND ERROR



[22:03:20] [Server thread/INFO]: |INFO| Mortar NMP Packet Listener Closed
[22:03:20] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[22:03:20] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:03:20] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[22:03:20] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[22:03:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[22:03:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[22:03:20] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:03:20] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[22:03:20] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:03:20] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[22:03:20] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[22:03:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[22:03:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[22:03:20] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:03:20] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[22:03:20] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:03:20] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[22:03:20] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[22:03:20] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[22:03:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[22:03:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[22:03:20] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[22:03:20] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cyberpwnn** [comment]
Are you reloading gloss or mortar with another plugin?

**Comment by cyberpwnn** [comment]
Is this Paper?

**Comment by Arasple** [comment]
I have the same issuse.
Using Paper-1.13.2

https://hastebin.com/puhojiqore.md

**Comment by cyberpwnn** [comment]
Should be fixed

**Comment by cyberpwnn** [comment]
Its a mortar bug so you need to update mortar
