### ISSUE TITLE
Error on /gloss reload

### ISSUE THREAD

**Issue by Firefox8821** [VolmitSoftware/Gloss#64]
```
[16:49:04] [Server thread/INFO]: Raimu_Akuna issued server command: /gloss reload
[16:49:04] [Server thread/INFO]: [Gloss] Disabling Gloss v1.0.26
[16:49:04] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[16:49:04] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.GlossPlugin.fullReload(GlossPlugin.java:132)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.command.CommandReload.handle(CommandReload.java:19)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:85)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:99)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onCommand(MortarPlugin.java:469)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[16:49:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:49:04] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[16:49:04] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.GlossPlugin.fullReload(GlossPlugin.java:132)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.command.CommandReload.handle(CommandReload.java:19)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:85)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:99)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onCommand(MortarPlugin.java:469)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[16:49:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:49:04] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[16:49:04] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.GlossPlugin.fullReload(GlossPlugin.java:132)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.command.CommandReload.handle(CommandReload.java:19)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:85)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:99)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onCommand(MortarPlugin.java:469)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[16:49:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:49:04] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[16:49:04] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[16:49:04] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:513)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:566)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.GlossPlugin.fullReload(GlossPlugin.java:132)
[16:49:04] [Server thread/WARN]: 	at com.volmit.gloss.command.CommandReload.handle(CommandReload.java:19)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:85)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.command.VirtualCommand.hit(VirtualCommand.java:99)
[16:49:04] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onCommand(MortarPlugin.java:469)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:49:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:49:04] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939)
[16:49:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[16:49:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:49:04] [Server thread/INFO]: [Gloss] Enabling Gloss v1.0.26*
[16:49:04] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader Gloss v1.0.26
[16:49:04] [Server thread/INFO]: ========================================================================================================================================
[16:49:04] [Server thread/INFO]: Gloss was developed by cyberpwn (VolmitSoftware). This is a BETA COPY. If this is published on spigot as someone else, please reject it.
[16:49:04] [Server thread/INFO]: ========================================================================================================================================
[16:49:04] [Server thread/INFO]: |INFO| Gloss Integration Connecting with PlaceholderAPI 2.9.2
[16:49:04] [Server thread/INFO]: |INFO| Gloss Integration Connecting with Vault 1.7.1-b91
[16:49:04] [Server thread/INFO]: |INFO| Gloss Integration Connecting with LightAPI 3.2.6 (build UNKNOWN)
[16:49:04] [Server thread/INFO]: |INFO| Gloss Integration Connecting with DeluxeChat 1.13.2
[16:49:17] [Server thread/INFO]: |INFO| Mortar Updater Checking for Updates
[16:49:17] [Server thread/INFO]: |INFO| Mortar Updater Mortar 1.0.45 is up to date!
```

**Comment by cyberpwnn** [comment]
Duplicate of #62
