### ISSUE TITLE
Error on Shutdown (1.13.2 Paper)

### ISSUE THREAD

**Issue by Firefox8821** [VolmitSoftware/Gloss#70]
[11:24:24] [Server thread/INFO]: |INFO| Mortar NMP Packet Listener Closed
[11:24:24] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[11:24:24] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:515)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:574)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[11:24:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:24:24] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[11:24:24] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:515)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:574)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[11:24:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:24:24] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[11:24:24] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:515)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:574)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[11:24:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by DavidRockin** [comment]
Issue remains on Mortar 1.0.70b1, Gloss 1.3.0b1, PaperSpigot 1.14.3
Possibly an issue with mortar?

```
 [18:18:01 WARN]: java.lang.NoSuchFieldException: knownCommands
[18:18:01 WARN]: at java.lang.Class.getDeclaredField(Class.java:2070)
[18:18:01 WARN]: at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[18:18:01 WARN]: at mortar.util.reflection.V.get(V.java:97)
[18:18:01 WARN]: at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:515)
[18:18:01 WARN]: at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:574)
[18:18:01 WARN]: at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[18:18:01 WARN]: at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[18:18:01 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[18:18:01 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[18:18:01 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
[18:18:01 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439)
[18:18:01 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432)
[18:18:01 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401)
[18:18:01 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:717)
[18:18:01 WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:737)
[18:18:01 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:949)
[18:18:01 WARN]: at java.lang.Thread.run(Thread.java:748)
```
