### ISSUE TITLE
Error startup

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Gloss#75]
Paper 1.13.2 build 639
Mortar 1.0.66
Gloss 1.0.29
```
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: Can not set boolean field com.volmit.gloss.Config.EMISSIVE_HOLOGRAMS to null value
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:80)
at java.lang.reflect.Field.set(Field.java:764)
at mortar.api.config.Configurator.stick(Configurator.java:193)
at mortar.api.config.Configurator.load(Configurator.java:59)
at com.volmit.gloss.Config.<init>(Config.java:17)
at com.volmit.gloss.GlossPlugin.start(GlossPlugin.java:144)
at mortar.bukkit.plugin.MortarPlugin.onEnable(MortarPlugin.java:83)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by DavidRockin** [comment]
Hi, thanks for the report. This was fixed in 1.300, hoping to release within the next 48 hours. Cheers.
