### ISSUE TITLE
Async Events

### ISSUE THREAD

**Issue by DavidRockin** [VolmitSoftware/Gloss#76]
Occurs on Paperspigot `1.14.3` with Mortar 1.0.70b1 and Gloss 1.3.0b1. Happens when changing items in hotbar, not tested for previous versions.

```
 [18:06:30 ERROR]: [Mortar] Error in onPacketInAsync().
java.lang.IllegalStateException: GlossPlayerScrollEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at com.volmit.gloss.controllers.PacketController$1.onPacket(PacketController.java:44) ~[?:?]
at mortar.api.nms.CatalystPacketListener$1.onPacketInAsync(CatalystPacketListener.java:95) ~[?:?]
at mortar.api.nms.TinyProtocol$1.channelRead(TinyProtocol.java:58) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at protocolsupport.utils.netty.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:56) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[Paper-1.14.3-b128.jar:git-Paper-128]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by DavidRockin** [comment]
fixed in a771cc0658a5b02c3a9ed24bb215387f257c28bd
