### ISSUE TITLE
 Can not set short field PacketPlayOutEntity.b to java.lang.Integer

### ISSUE THREAD

**Issue by DavidRockin** [VolmitSoftware/Gloss#77]
Occurs on Paperspigot 1.14.3 with Mortar 1.0.70b1 and Gloss 1.3.0b1. Happens when viewing a hologram. Issue with mortar.

``` [18:10:04 WARN]: java.lang.IllegalArgumentException: Can not set short field net.minecraft.server.v1_14_R1.PacketPlayOutEntity.b to java.lang.Integer
[18:10:04 WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[18:10:04 WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[18:10:04 WARN]: at sun.reflect.UnsafeShortFieldAccessorImpl.set(UnsafeShortFieldAccessorImpl.java:90)
[18:10:04 WARN]: at java.lang.reflect.Field.set(Field.java:764)
[18:10:04 WARN]: at mortar.api.nms.Catalyst14.moveEntityRelative(Catalyst14.java:574)
[18:10:04 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.sendMove(GlossDisplayComponent.java:330)
[18:10:04 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.update(GlossDisplayComponent.java:148)
[18:10:04 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.update(GlossDisplayComponent.java:249)
[18:10:04 WARN]: at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:165)
[18:10:04 WARN]: at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
[18:10:04 WARN]: at com.volmit.gloss.context.GlossContextualView.lambda$update$4(GlossContextualView.java:228)
[18:10:04 WARN]: at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[18:10:04 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[18:10:04 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[18:10:04 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[18:10:04 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```

**Comment by DavidRockin** [comment]
Also side note to verify and double check all reflection methods/properties for catalyst 14.
