### ISSUE TITLE
Gloss Chat Bubbles error

### ISSUE THREAD

**Issue by paz** [VolmitSoftware/Gloss#86]
```>.... [11:47:22 ERROR]: Could not pass event AsyncPlayerChatEvent to GlossChatBubbles v1.2.0
java.lang.NullPointerException: null
at com.volmit.gloss.chatbubbles.GlossChatBubbles.on(GlossChatBubbles.java:60) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor300.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-163]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-163]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-163]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.4.jar:git-Paper-163]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```
**Server and Plugin Informations**
 - Installed plugins: (28): BlocksHub, CasualProtector*, ChestSort, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FastAsyncWorldEdit, Gloss*, GlossChatBubbles*, GlossDamageIndicators*, IllegalStack, ImageMaps*, LiteBans, LuckPerms, LumberJack, mcMMO, Mortar*, MOTD, Plan, ProtocolLib, React*, Recount, Vault, VeinMiner, WorldEdit
 - Gloss and Mortar Version: gloss 1.3.1, mortar 1.0.71
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Paper 1.14.4 b163
 - Operating System (if applicable): centos 7 x64

**Comment by DavidRockin** [comment]
From now on can you please use the issue templates. Thanks,

**Comment by DavidRockin** [comment]
You should delete the config file for GlossChatBubbles and restart your server. Not sure why the config isnt auto updating.
